---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.3.0
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
# #%matplotlib notebook
# %matplotlib inline
from matplotlib import rc
rc('figure',figsize=(9,4.5))
rc('font',size=12)
rc('text',usetex=False)

from qubicpack.qubicfp import qubicfp
import qubic.fibtools as ft
import qubic.plotters as p
import qubic.lin_lib as ll
import qubic.demodulation_lib as dl
import satorchipy as stpy
from pysimulators import FitsArray

import numpy as np
from matplotlib.pyplot import *
import matplotlib.mlab as mlab
import scipy.ndimage.filters as f
import glob
import string
import scipy.signal as scsig
from scipy import interpolate
import datetime as dt
import pickle
from importlib import reload
```

# Setting the directory containing data

Here are the vailable data:
### 2020-01-14: 
- 2020-01-14_18.38.23__ScanFast_Speed_VE5_DeltaAz_40_DeltaEl_30_NScans_151_Cycle_0: 
    - Long acquisition during the night with SOurce Modulation 
    - Note that the computer experienced a reboot during the night (at ~5AM) due to some windows update probably. As a result the scan is not fully complete and STeve had to modify by hand some fits files in order to make them readable. After discussion with Wilfried, it seems that there is a solution to this kind of issues in the way QS files a re written and this will soon be implemented.
    - Edit (16/01/2020): Steve has corrected the dataset so in principle it can be read and analysed
    
### 2020-01-15: 
- 2020-01-15_21.34.32__ScanFast_Speed_VE10_DeltaAz_40_DeltaEl_30_NScans_151_Cycle_0:
    - Long acquisition overnight. It was intended to be without the modulation of the source but acttually the source was modulating in sine. So it should be analysed with the current cript instead of the one not using modulation.

### 2020-03-16: 
- 2020-03-16_10.55.31__ScanFast_Speed_VE10_DeltaAz_10_DeltaEl_10_NScans_1_Cycle_0:
    - Short test
- 2020-03-16_11.04.58__ScanFast_Speed_VE12_DeltaAz_50_DeltaEl_10_NScans_1_Cycle_0:
    - short test
- 2020-03-16_11.14.29__ScanFast_Speed_VE12_DeltaAz_50_DeltaEl_30_NScans_51_Cycle_0:
    - interrupted
- 2020-03-16_12.46.27__ScanFast_Speed_VE12_DeltaAz_50_DeltaEl_30_NScans_51_Cycle_0:
    - Full Cycle



```{python}
day = '2020-01-14'
keyword = '*ScanFast*'
#data_dir = '/qubic/Data/Calib-TD/'+day+'/'
#data_dir = '/Users/hamilton/Qubic/Calib-TD/'+day+'/'
data_dir = '/home/james/QUBICdata/'+day+'/'
dirs = np.sort(glob.glob(data_dir+keyword))

print (dirs)

```

```{python}
ifile = 0
thedir = dirs[ifile]
print(thedir)
a = qubicfp()
a.read_qubicstudio_dataset(thedir)
```

```{python}
print(a.hk.keys())
```

```{python}
print(a.hk['INTERN_HK'].keys())
```

```{python}
print(a.hk['EXTERN_HK'].keys())
```

```{python}
print(a.hk['CALSOURCE-CONF'].keys())
```

```{python}
a.ADU2I
```

```{python}
rc('figure',figsize=(12,12))

time_azel = a.timeaxis(datatype='hk',axistype='pps')
az = a.azimuth()
el = a.elevation()

t_src = a.calsource()[0]
data_src = a.calsource()[1]

t0 = time_azel[0]

subplot(2,2,1)
plot((time_azel-t0)/3600, az,',')
xlabel('Time [h]')
ylabel('Az')
subplot(2,2,2)
plot((time_azel-t0)/3600, el,',')
xlabel('Time [h]')
ylabel('El')
ylim(30,70)

subplot(2,2,3)
plot(az*np.cos(np.radians(el)), el,',')
xlabel('Az')
ylabel('El')

subplot(2,2,4)
plot((t_src-t0)/3600, data_src,',')
xlabel('Time [h]')
ylabel('Src Data')

```

```{python}
print(az.shape)
```

```{python}
TESNum = 95
asic = 1
tod = a.timeline(TES=TESNum,asic=asic)
tt = a.timeaxis(axistype='pps', asic=asic)

subplot(2,1,1)
plot((tt-t0)/3600, dl.renorm(tod), 
     label='Data TES {} ASIC {}'.format(TESNum,asic))
plot((t_src-t0)/3600, dl.renorm(data_src)-5, label='source')
xlabel('Hours')
legend(loc='upper left')
title(thedir)
ylim(-10,10)

subplot(2,1,2)
tzoom = 1.2940
dtzoom = 0.005
oktime_d = np.abs((tt-t0)/3600-tzoom) < dtzoom
oktime_s = np.abs((t_src-t0)/3600-tzoom) < dtzoom
plot((tt-t0)[oktime_d]/3600, dl.renorm(tod[oktime_d]), 
     label='Data TES {} ASIC {}'.format(TESNum,asic))
plot((t_src[oktime_s]-t0)/3600, dl.renorm(data_src[oktime_s]), label='source')
xlabel('Hours')
legend(loc='upper left')
title(thedir)

```

```{python}
rc('figure',figsize=(13,8))
#### Filtering
reload(ft)

thefreqmod = 1.

period = 1./ thefreqmod
lowcut = 0.5
highcut = 20

xmin = 0.01
xmax = 90.
ymin = 1e1
ymax = 1e17

############ Power spectrum
spectrum_f, freq_f = ft.power_spectrum(tt, tod, rebin=True)
plot(freq_f, f.gaussian_filter1d(spectrum_f,1),label='Raw Data')
yscale('log')
xscale('log')
xlabel('Frequency [Hz]')
ylabel('Power Spectrum')
xlim(xmin, xmax)
ylim(ymin, ymax)
title('TES {} ASIC {}'.format(TESNum,asic))

for i in range(10):
    plot([1./period*i,1./period*i],[ymin,ymax],'k--',alpha=0.3)

plot([lowcut, lowcut],[ymin,ymax],'k')
plot([highcut, highcut],[ymin,ymax],'k')
legend()

########## New Power spectrum
nharm = 10
notch = np.array([[1.724, 0.005, nharm]])
newdata = ft.filter_data(tt, tod, lowcut, highcut, notch=notch, rebin=True, verbose=True, order=5)
spectrum_f2, freq_f2 = ft.power_spectrum(tt, newdata, rebin=True)
plot(freq_f2, f.gaussian_filter1d(spectrum_f2,1),label='Filtered data')
for i in range(nharm):
    plot([notch[0,0]*(i+1),notch[0,0]*(i+1)], [ymin,ymax],'m:')
legend(loc='upper left')

tight_layout()
```

```{python}
plot((tt-t0)/3600, dl.renorm(newdata), 
     label='Data TES {} ASIC {}'.format(TESNum,asic))
plot((t_src-t0)/3600, dl.renorm(data_src)-5, label='source')
xlabel('Hours')
legend()
title(thedir)
ylim(-20,20)

```

```{python}
tzoom = 2.101
dtzoom = 0.003
oktime_d = np.abs((tt-t0)/3600-tzoom) < dtzoom
oktime_s = np.abs((t_src-t0)/3600-tzoom) < dtzoom
plot((tt-t0)[oktime_d]/3600, dl.renorm(newdata[oktime_d]), 
     label='Data TES {} ASIC {}'.format(TESNum,asic))
plot((t_src[oktime_s]-t0)/3600, dl.renorm(data_src[oktime_s]), label='source')
xlabel('Hours')
legend()
title(thedir)

```

Now we apply demodualtion with the source data

```{python}
reload(dl)
##### Filtering to be used
lowcut = 0.5
highcut = 70
nharm = 10
notch = np.array([[1.724, 0.005, nharm]])
fourier_cuts = [lowcut, highcut, notch]

TESNum = 96
asic = 1

tod = a.timeline(TES=TESNum,asic=asic)
tt = a.timeaxis(axistype='pps', asic=asic)

src = [tt, np.interp(tt, t_src, data_src)]
period = 1.
newt_demod, amp_demod, errors_demod = dl.demodulate_methods([tt, tod],
                                                            1./period, 
                                                            src_data_in=src,
                                                            method='demod_quad', remove_noise=True,
                                                           fourier_cuts=fourier_cuts)
tzoom = 2.101
dtzoom = 0.03
oktime_d = np.abs((tt-t0)/3600-tzoom) < dtzoom
plot((tt[oktime_d]-t0)/3600, (newdata[oktime_d]), 
     label='Data TES {} ASIC {}'.format(TESNum,asic))

okdemod = np.abs((newt_demod-t0)/3600-tzoom) < dtzoom
plot((newt_demod[okdemod]-t0)/3600, (amp_demod[okdemod]), label='demodulated')

xlabel('Hours')
legend()
title(thedir)

```

```{python}
"""load data and go from here"""
time_azel = a.timeaxis(datatype='hk',axistype='pps')
az = a.azimuth()
el = a.elevation()

t_src = a.calsource()[0]
data_src = a.calsource()[1]

#t0 = time_azel[0]

reload(dl)
##### Filtering to be used
lowcut = 0.5
highcut = 70
nharm = 10
notch = np.array([[1.724, 0.005, nharm]])
fourier_cuts = [lowcut, highcut, notch]

TESNum = 96
asic = 1

tod = a.timeline(TES=TESNum,asic=asic)
tt = a.timeaxis(axistype='pps', asic=asic)

src = [tt, np.interp(tt, t_src, data_src)]
period = 1.
newt_demod, amp_demod, errors_demod = dl.demodulate_methods([tt, tod],
                                                            1./period, 
                                                            src_data_in=src,
                                                            method='demod_quad', remove_noise=True,
                                                           fourier_cuts=fourier_cuts)
```

```{python}
print(amp_demod.shape)
```

```{python}
oktime_azel = np.abs((time_azel-t0)/3600-tzoom) < dtzoom
print(el[oktime_azel])
```

```{python}
newaz = np.interp(newt_demod, time_azel, az)
newel = np.interp(newt_demod, time_azel, el)
azmin = min(az)
azmax = max(az)
elmin = min(el)
elmax = max(el)
naz = 81
nel = 81
mymap, azmap, elmap = dl.coadd_flatmap(amp_demod, newaz, newel, 
                                    filtering=None,
                                    azmin=azmin, azmax=azmax, 
                                    elmin=elmin, elmax=elmax, 
                                    naz=naz,nel=nel)

```

```{python}
print(newaz.shape, mymap.shape, azmap.shape)
print(min(el), max(el), min(az), max(az))
```

```{python}
imshow(mymap, aspect='equal',
       extent=[np.cos(np.radians(50))*azmin, np.cos(np.radians(50))*azmax, elmax, elmin])
title('TES {}'.format(TESNum))
xlabel('Cos(50) x Az')
ylabel('El')
colorbar()
```

```{python}
len(amp_demod)
```

```{python}
print(len(amp_demod[:2500000]))
```

```{python}
amp_demod = amp_demod[:2500000]
```

```{python}
# also try saving a.timeaxis
```

Now loop on all TES and all ASICs

```{python}
reload(dl)
### Now do all maps with the same cuts
###
Period = 1.

##### Filtering to be used
lowcut = 0.5
highcut = 70
nharm = 10
notch = np.array([[1.724, 0.005, nharm]])
fourier_cuts = [lowcut, highcut, notch]

amps_demod = np.zeros((256, len(amp_demod)))

for asic in [1,2]:
    tt = a.timeaxis(axistype='pps', asic=asic)
    src = [tt, np.interp(tt, t_src, data_src)]
    for i in range(128):
        print('Mapmaking for Asic {} TES {}'.format(asic,i+1))    
        tod = a.timeline(TES=i+1,asic=asic)

        print('- Demodulation')
        newt_demod, amps_demod[i+128*(asic-1),:], errors_demod = dl.demodulate_methods([tt, tod],
                                                                    1./period, 
                                                                    src_data_in=src,
                                                                    method='demod_quad', remove_noise=True,
                                                                   fourier_cuts=fourier_cuts)

```

```{python}
print(amps_demod.shape, az.shape)
"""save the az el files for flats..."""
#appears get flatmap actually wants size 51
from pysimulators import FitsArray as fa
fa(azmap).save('/home/james/synthbeamdata/2020-01-14/Flat/azimuth.fits')
fa(elmap).save('/home/james/synthbeamdata/2020-01-14/Flat/elevation.fits')
```

```{python}
#check values of map
print(np.mean(amps_demod[200,:]))
```

```{python}
"""kill unneccessary to save memory..."""
del azmap, elmap, errors_demod, src, tod, tt, t_src, data_src
```

```{python}

nmaps = 256
mapdata = np.zeros((256, nel, naz))
newaz = np.interp(newt_demod, time_azel, az)
newel = np.interp(newt_demod, time_azel, el)

mapdata, azmap, elmap = dl.coadd_flatmap(amps_demod, newaz, newel, 
                                                                filtering=None,
                                                                azmin=azmin, azmax=azmax, 
                                                                elmin=elmin, elmax=elmax, 
                                                                naz=naz,nel=nel)

```

```{python}
print(newaz.shape, newel.shape, azmap.shape, elmap.shape, mapdata.shape)
```

```{python}
TESNum = 200
ites = TESNum-1
mm, ss = ft.meancut(mapdata[ites,:,:],3)
# imshow(-mapdata[ites,:,:], aspect='equal',
#        extent=[np.cos(np.radians(50))*azmin, np.cos(np.radians(50))*azmax, elmin, elmax],
#        vmin=mm-ss, vmax=mm+30*ss)
# title('TES {}'.format(ites+1))

imshow(mapdata[ites,:,:], aspect='equal',
       extent=[np.cos(np.radians(50))*azmin, np.cos(np.radians(50))*azmax, elmin, elmax])
title('TES {}'.format(ites+1))

```

```{python}
rc('figure',figsize=(16,8))
nnx = 5
nny=2
k=0
nplots = int(256/nnx/nny)+1


for k in range(nplots):
    figure()
    for i in range(nnx*nny):
        ites = i+k*nnx*nny
        if ites < 256:
            subplot(nny,nnx,i+1)
            mm, ss = ft.meancut(mapdata[ites,:,:],3)
            imshow(-mapdata[ites,:,:], aspect='equal',
                   extent=[np.cos(np.radians(50))*azmin, np.cos(np.radians(50))*azmax, elmin, elmax],
                   vmin=mm-ss, vmax=mm+30*ss)
            title('TES {}'.format(ites+1))
            savefig('toto{}.png'.format(k))
    tight_layout()
    show()
```

```{python}
TESNum = 213
mm, ss = ft.meancut(mapdata[TESNum-1,:,:],3)
imshow(-mapdata[TESNum-1,:,:], aspect='equal',
       extent=[np.cos(np.radians(50))*azmin, np.cos(np.radians(50))*azmax, elmin, elmax],
       vmin=mm-3*ss, vmax=mm+50*ss)
title('TES {}'.format(TESNum))

```

```{python}
az2d, el2d = np.meshgrid(azmap,elmap)

from mpl_toolkits.mplot3d import Axes3D

fig = figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(az2d, el2d, -mapdata[TESNum-1,:,:], cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)

```

```{python}
#save arrays as fits files
#print((mapdata[:,:,:].shape))
#print(mapdata[:,0,0])
# freq = '150GHz'
# print(day)
# path = '/home/james/synthbeamdata/'+day+'/Healpix/'


# for mp in range(len(mapdata[:,0,0])):
#     #print(mapdata[mp,0,0].shape)
#     tes = str(mp+1)
#     FitsArray(mapdata[mp,:,:]).save(path+'healpix_'+'TESNum_'+tes+'.fits')
```

```{python}
print(mapdata[:,0,0].shape)
```

```{python}
"""martins solution"""
print(np.shape(mapdata))
import os
#os.mkdir('/home/james/synthbeamdata/2020-03-16/Flat')
for i in range(256):
    print("saving flat map for tes {}".format(i+1))
    FitsArray(mapdata[i,:,:]).save('/home/james/synthbeamdata/2020-01-14/Flat/imgflat_TESNum_{}.fits'.format(i+1))
```

```{python}
import healpy as hp
from qubic import demodulation_lib as dl
newaz = np.interp(newt_demod, time_azel, az)
newel = np.interp(newt_demod, time_azel, el)
print(amp_demod.shape)
hpmapa = dl.scan2hpmap(128, newaz*np.cos(np.radians(50)), newel-50, amp_demod )


```

```{python}
hp.mollview(hpmapa)
hp.gnomview(hpmapa,reso=10,max=np.max(hpmapa)/5,min=0)
```

```{python}

```

```{python}
"""need to create array of demondulated signals... this already exists here"""
print(amps_demod.shape)
print(hpmapa)
# demodpath = '/home/james/synthbeamdata/2020-03-16/amps_demod/'
# fname = 'amps_demod'
# np.savetxt(demodpath+fname, amps_demod, delimiter=',')
# ad = np.loadtxt(demodpath+fname, delimiter=',')
# print(ad.shape)
```

```{python}

newaz = np.interp(newt_demod, time_azel, az)
newel = np.interp(newt_demod, time_azel, el)
print(amps_demod.shape)
hpmaps = np.array([])
# for tes in np.linspace(0,255, 256, dtype=int):
#     print(tes)
#     hpmap = dl.scan2hpmap(128, newaz*np.cos(np.radians(50)), newel-50, amps_demod[tes,:])
#     FitsArray(hpmap).save('/home/james/synthbeamdata/2020-03-16/Flat/imgflat_TESNum_{}.fits'.format(i+1))
def write_mapjames(filename, map, mask=None, nest=False, dtype=np.float32,
              coord=None, extnames=None, compress=True):
    """
    Write one or more compressed (complete or partial) Healpix maps
    as FITS file.

    Parameters
    ----------
    filename : str
        The FITS file name.
    map : array of shape (N) or (N, M)
        The partial or complete input Healpix maps.
    mask : bool array, optional
        The mask controlling partial maps, such as complete[mask] == partial
        (True means valid).
    nest : bool, optional
        If True, ordering scheme is assumed to be NESTED, otherwise, RING.
        Default: RING. The map ordering is not modified by this function,
        the input map array should already be in the desired ordering.
    coord : str
        The coordinate system, typically 'E' for Ecliptic, 'G' for Galactic or
        'C' for Celestial (equatorial).
    extnames : str or list
        The FITS extension names, by default, we use:
            - I_STOKES for 1 component,
            - I/Q/U_STOKES for 3 components,
            - II, IQ, IU, QQ, QU, UU for 6 components,
            - DATA_0, DATA_1... otherwise
    """
    map = np.asanyarray(map, order='f') #XXX astropy issue #2150
    if map.ndim not in (1, 2):
        raise ValueError('Invalid dimensions of the healpix map(s).')
    if map.ndim == 1:
        map = map.reshape(-1, 1)
    nmaps = map.shape[1]
    if mask is not None:
        mask = np.asarray(mask, np.uint8)
        if mask.ndim != 1:
            raise ValueError('Invalid dimensions of healpix the mask.')
        npix = mask.size
    else:
        npix = map.shape[0]
    try:
        coord = map.header['coordsys'].upper()
    except (AttributeError, KeyError):
        pass
    try:
        ordering = map.header['ordering'].upper()
        if ordering not in ('NESTED', 'RING'):
            raise ValueError("Invalid ordering scheme '{}'.".format(ordering))
    except (AttributeError, KeyError):
        ordering = 'NESTED' if nest else 'RING'
    print("npix", npix)
    nside = hp.npix2nside(npix)
    #nside = hp.get_nside(map)
    print("npix nside", npix, nside)

    if compress and map.dtype != int: #XXX avoid crash: astropy issue #2153
        _imageHDU = fits.CompImageHDU
    else:
        _imageHDU = fits.ImageHDU

    primary = fits.PrimaryHDU()
    primary.header['nside'] = nside, 'Resolution parameter of HEALPIX'
    primary.header['ordering'] = (ordering, 'Pixel ordering scheme, '
                                  'either RING or NESTED')
    if coord:
        primary.header['coordsys'] = (coord, 'Ecliptic, Galactic or Celestial '
                                      '(equatorial)')
    primary.header['format'] = 'HPX_QB'
    primary.header['nmaps'] = nmaps
    primary.header['hasmask'] = mask is not None
    if hasattr(map, 'header'):
        for key in sorted(set(map.header.keys()) -
                          set(('nside', 'format', 'nmaps', 'hasmask'))):
            primary.header[key] = map.header[key]
    hdus = [primary]

    if mask is not None:
        hdu = fits.CompImageHDU(mask)
        hdu.header.set('name', 'VALIDMASK')
        hdus.append(hdu)

    if extnames is None:
        extnames = _default_extnames.get(
            nmaps, ('DATA_{}'.format(i + 1) for i in range(nmaps)))

    for m, extname in zip(map.T, extnames):
        hdu = _imageHDU(np.array(m, dtype=dtype, copy=False))
        hdu.header.set('name', extname)
        hdus.append(hdu)

    fits.HDUList(hdus).writeto(filename, clobber=True)
from qubic.io import write_map
from astropy.io import fits
amps_test = amps_demod[0,0:1589951]
write_map('/home/james/synthbeamdata/2020-03-16/Healpix/healpix_TESNum_96.fits', hpmapa)
```

```{python}
import qubic.sb_fitting as sbfit
directory = '/home/james/synthbeamdata/2020-03-16'
#directory = '/home/james/synthbeamdata/150GHz-2019-04-06'

#hp.gnomview(sb, rot=[0,90], reso=10)
#hp.gnomview(sb, rot=[0,90], reso=10, cmap='jet',max=np.max(sb)/5,min=0)

hpmap = sbfit.get_hpmap(96, directory)
hp.gnomview(hpmap, reso=10, title='TES #{}'.format(96),cmap='jet',max=np.max(hpmap)/5,min=0)

print(hpmap.shape)
```

```{python}
"""for each demodulated signal make a hpmap and save it"""
newaz = np.interp(newt_demod, time_azel, az)
newel = np.interp(newt_demod, time_azel, el)
print(amps_demod.shape)

path = '/home/james/synthbeamdata/'+day+'/Healpix/'

for tes in np.linspace(0,255, 256, dtype=int):
    tesnum=str(tes+1)
    print("tes idx, tesnum ", tes, tes+1)
    hpmap = dl.scan2hpmap(128, newaz*np.cos(np.radians(50)), newel-50, amps_demod[tes,:])
    write_map(path+'healpix_'+'TESNum_'+tesnum+'.fits', hpmap)
```

```{python}
#print(az.shape, newaz.shape, az, newaz*np.cos(np.radians(50)), newel-50)

print("az", min(az), max(az), min(newaz), max(newaz))
print("el",min(el), max(el), min(newel), max(newel))

print("con az",min(newaz*np.cos(np.radians(50))), max(newaz*np.cos(np.radians(50))))
print("con el", min(newel-50), max(newel-50))
```

```{python}
TESNum=96
hpmap = sbfit.get_hpmap(TESNum, directory)
hp.gnomview(hpmap, reso=10, title='TES #{}'.format(TESNum),cmap='jet',max=np.max(hpmap)/5,min=0)
```

```{python}

```
