---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.6.0
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# This is a demodulation script that also builds Flat maps and Healpix maps
The demodulation is based on JC's demodulation
But for the ghost data set in January the TOD data lengths were not the same (~ 5800000 / 5800009) for both ASICS so at some point I split of the processing per asic and combined later.
Then making the map files and some plotting is included

```{python}
# #%matplotlib notebook
# %matplotlib inline
from matplotlib import rc
rc('figure',figsize=(9,4.5))
rc('font',size=12)
rc('text',usetex=False)

from qubicpack.qubicfp import qubicfp
import qubic.fibtools as ft
import qubic.plotters as p
import qubic.lin_lib as ll
import qubic.demodulation_lib as dl
import satorchipy as stpy
from pysimulators import FitsArray

import numpy as np
from matplotlib.pyplot import *
import matplotlib.mlab as mlab
import scipy.ndimage.filters as f
import glob
import string
import scipy.signal as scsig
from scipy import interpolate
import datetime as dt
import pickle
from importlib import reload
```

# Setting the directory containing data

Here are the vailable data:
### 2020-01-14: 
- 2020-01-14_18.38.23__ScanFast_Speed_VE5_DeltaAz_40_DeltaEl_30_NScans_151_Cycle_0: 
    - Long acquisition during the night with SOurce Modulation 
    - Note that the computer experienced a reboot during the night (at ~5AM) due to some windows update probably. As a result the scan is not fully complete and STeve had to modify by hand some fits files in order to make them readable. After discussion with Wilfried, it seems that there is a solution to this kind of issues in the way QS files a re written and this will soon be implemented.
    - Edit (16/01/2020): Steve has corrected the dataset so in principle it can be read and analysed

```{python}
day = '2020-01-14'
keyword = '*ScanFast*'
data_dir = '/sps/hep/qubic/Data/Calib-TD/'+day+'/'
dirs = np.sort(glob.glob(data_dir+keyword))
print(dirs)
```

```{python}
ifile = 0
thedir = dirs[ifile]
print(thedir)
a = qubicfp()
a.read_qubicstudio_dataset(thedir)
```

```{python}
print(a.hk.keys())
```

```{python}
print(a.hk['INTERN_HK'].keys())
```

```{python}
print(a.hk['EXTERN_HK'].keys())
```

```{python}
print(a.hk['CALSOURCE'].keys())
```

```{python}
a.hk['CALSOURCE-CONF']={}
a.hk['CALSOURCE-CONF']['MsgStr'] = ['1579027126.204764 1579027105.472763  modulator:ON calsource:ON lamp:OFF amplifier:ON arduino:UNKNOWN amplifier:filter_mode=12db_low_pass amplifier:dynamic_range=high amplifier:gain=10000 amplifier:filter_low_frequency=0.30Hz amplifier:coupling=DC amplifier:invert=on calsource:frequency=+150.000000GHz synthesiser:frequency=+12.500000GHz modulator:SHAPE=SINE modulator:FREQUENCY=+1.000000Hz modulator:AMPLITUDE=+1.000000Vpp modulator:OFFSET=+1.500000Vdc modulator:DUTY_CYCLE=+50.000000%']

```

```{python}
#print(a.hk['CALSOURCE-CONF']['MsgStr']['frequency'])
```

```{python}
rc('figure',figsize=(12,12))

time_azel = a.timeaxis(datatype='hk',axistype='pps')
az = a.azimuth()
el = a.elevation()

t_src = a.calsource()[0]
data_src = a.calsource()[1]

t0 = time_azel[0]

subplot(2,2,1)
plot((time_azel-t0)/3600, az,',')
xlabel('Time [h]')
ylabel('Az')
subplot(2,2,2)
plot((time_azel-t0)/3600, el,',')
xlabel('Time [h]')
ylabel('El')
ylim(30,70)

subplot(2,2,3)
plot(az*np.cos(np.radians(el)), el,',')
xlabel('Az')
ylabel('El')

subplot(2,2,4)
plot((t_src-t0)/3600, data_src,',')
xlabel('Time [h]')
ylabel('Src Data')
```

```{python}
print(az.shape)
```

```{python}
TESNum = 95
asic = 1
tod = a.timeline(TES=TESNum,asic=asic)
tt = a.timeaxis(axistype='pps', asic=asic)

subplot(2,1,1)
plot((tt-t0)/3600, dl.renorm(tod), 
     label='Data TES {} ASIC {}'.format(TESNum,asic))
plot((t_src-t0)/3600, dl.renorm(data_src)-5, label='source')
xlabel('Hours')
legend(loc='upper left')
title(thedir)
ylim(-10,10)

subplot(2,1,2)
tzoom = 1.2940
dtzoom = 0.005
oktime_d = np.abs((tt-t0)/3600-tzoom) < dtzoom
oktime_s = np.abs((t_src-t0)/3600-tzoom) < dtzoom
plot((tt-t0)[oktime_d]/3600, dl.renorm(tod[oktime_d]), 
     label='Data TES {} ASIC {}'.format(TESNum,asic))
plot((t_src[oktime_s]-t0)/3600, dl.renorm(data_src[oktime_s]), label='source')
xlabel('Hours')
legend(loc='upper left')
title(thedir)

```

```{python}
rc('figure',figsize=(13,8))
#### Filtering
reload(ft)

thefreqmod = 1.

period = 1./ thefreqmod
lowcut = 0.5
highcut = 20

xmin = 0.01
xmax = 90.
ymin = 1e1
ymax = 1e17

############ Power spectrum
spectrum_f, freq_f = ft.power_spectrum(tt, tod, rebin=True)
plot(freq_f, f.gaussian_filter1d(spectrum_f,1),label='Raw Data')
yscale('log')
xscale('log')
xlabel('Frequency [Hz]')
ylabel('Power Spectrum')
xlim(xmin, xmax)
ylim(ymin, ymax)
title('TES {} ASIC {}'.format(TESNum,asic))

for i in range(10):
    plot([1./period*i,1./period*i],[ymin,ymax],'k--',alpha=0.3)

plot([lowcut, lowcut],[ymin,ymax],'k')
plot([highcut, highcut],[ymin,ymax],'k')
legend()

########## New Power spectrum
nharm = 10
notch = np.array([[1.724, 0.005, nharm]])
newdata = ft.filter_data(tt, tod, lowcut, highcut, notch=notch, rebin=True, verbose=True, order=5)
spectrum_f2, freq_f2 = ft.power_spectrum(tt, newdata, rebin=True)
plot(freq_f2, f.gaussian_filter1d(spectrum_f2,1),label='Filtered data')
for i in range(nharm):
    plot([notch[0,0]*(i+1),notch[0,0]*(i+1)], [ymin,ymax],'m:')
legend(loc='upper left')

tight_layout()
```

```{python}
plot((tt-t0)/3600, dl.renorm(newdata), 
     label='Data TES {} ASIC {}'.format(TESNum,asic))
plot((t_src-t0)/3600, dl.renorm(data_src)-5, label='source')
xlabel('Hours')
legend()
title(thedir)
ylim(-20,20)

```

```{python}
tzoom = 2.101
dtzoom = 0.003
oktime_d = np.abs((tt-t0)/3600-tzoom) < dtzoom
oktime_s = np.abs((t_src-t0)/3600-tzoom) < dtzoom
plot((tt-t0)[oktime_d]/3600, dl.renorm(newdata[oktime_d]), 
     label='Data TES {} ASIC {}'.format(TESNum,asic))
plot((t_src[oktime_s]-t0)/3600, dl.renorm(data_src[oktime_s]), label='source')
xlabel('Hours')
legend()
title(thedir)

```

```{python}
"""setup vars here"""
time_azel = a.timeaxis(datatype='hk',axistype='pps')
t0 = time_azel[0]
az = a.azimuth()
el = a.elevation()

t_src = a.calsource()[0]
data_src = a.calsource()[1]
```

```{python}
"""setup demod for asic1"""
reload(dl)
##### Filtering to be used
lowcut = 0.5
highcut = 70
nharm = 10
notch = np.array([[1.724, 0.005, nharm]])
fourier_cuts = [lowcut, highcut, notch]

TESNum = 93
asic = 1

tod = a.timeline(TES=TESNum,asic=asic)
tt = a.timeaxis(axistype='pps', asic=asic)

src = [tt, np.interp(tt, t_src, data_src)]
period = 1.
newt_demoda1, amp_demodasic1, errors_demod = dl.demodulate_methods([tt, tod],
                                                            1./period, 
                                                            src_data_in=src,
                                                            method='demod_quad', remove_noise=True,
                                                            fourier_cuts=fourier_cuts)
# tzoom = 2.101
# dtzoom = 0.03
# oktime_d = np.abs((tt-t0)/3600-tzoom) < dtzoom
# plot((tt[oktime_d]-t0)/3600, (newdata[oktime_d]), 
#      label='Data TES {} ASIC {}'.format(TESNum,asic))

# okdemod = np.abs((newt_demod-t0)/3600-tzoom) < dtzoom
# plot((newt_demod[okdemod]-t0)/3600, (amp_demodasic1[okdemod]), label='demodulated')

# xlabel('Hours')
# legend()
# title(thedir)

print("amp demod size asic1", len(amp_demodasic1))
print("tt tod", len(tt), len(tod))
```

```{python}
"""setup demod for asic2"""
reload(dl)
##### Filtering to be used
lowcut = 0.5
highcut = 70
nharm = 10
notch = np.array([[1.724, 0.005, nharm]])
fourier_cuts = [lowcut, highcut, notch]

TESNum = 93
asic = 2

tod = a.timeline(TES=TESNum,asic=asic)
tt = a.timeaxis(axistype='pps', asic=asic)

src = [tt, np.interp(tt, t_src, data_src)]
period = 1.
newt_demoda2, amp_demodasic2, errors_demod = dl.demodulate_methods([tt, tod],
                                                            1./period, 
                                                            src_data_in=src,
                                                            method='demod_quad', remove_noise=True,
                                                           fourier_cuts=fourier_cuts)
# tzoom = 2.101
# dtzoom = 0.03
# oktime_d = np.abs((tt-t0)/3600-tzoom) < dtzoom
# plot((tt[oktime_d]-t0)/3600, (newdata[oktime_d]), 
#      label='Data TES {} ASIC {}'.format(TESNum,asic))

# okdemod = np.abs((newt_demod-t0)/3600-tzoom) < dtzoom
# plot((newt_demod[okdemod]-t0)/3600, (amp_demodasic2[okdemod]), label='demodulated')

# xlabel('Hours')
# legend()
# title(thedir)

print("amp demod size asic2", len(amp_demodasic2))
print("tt tod", len(tt), len(tod))
```

```{python}
len(amp_demodasic2)
```

```{python}
oktime_azel = np.abs((time_azel-t0)/3600-tzoom) < dtzoom
print(el[oktime_azel])
```

```{python}
az = a.azimuth()
el = a.elevation()
print(min(az), max(az), min(el), max(el))

```

```{python}
"""test maps for each asic"""
newaza1 = np.interp(newt_demoda1, time_azel, az)
newela1 = np.interp(newt_demoda1, time_azel, el)
newaza2 = np.interp(newt_demoda2, time_azel, az)
newela2 = np.interp(newt_demoda2, time_azel, el)
azmin = min(az)
azmax = max(az)
elmin = min(el)
elmax = max(el)
naz = 101
nel = 101
mymapa1, azmap, elmap = dl.coadd_flatmap(amp_demodasic1, newaza1, newela1, 
                                    filtering=None,
                                    azmin=azmin, azmax=azmax, 
                                    elmin=elmin, elmax=elmax, 
                                    naz=naz,nel=nel)

mymapa2, azmap, elmap = dl.coadd_flatmap(amp_demodasic2, newaza2, newela2, 
                                    filtering=None,
                                    azmin=azmin, azmax=azmax, 
                                    elmin=elmin, elmax=elmax, 
                                    naz=naz,nel=nel)

```

```{python}
print(mymapa1.shape, mymapa2.shape)
```

```{python}
t_platform = a.timeaxis(datatype='platform',axistype='pps')
print(t_platform.shape)
```

```{python}
imshow(mymapa2, aspect='equal',
       extent=[np.cos(np.radians(50))*azmin, np.cos(np.radians(50))*azmax, elmax, elmin])
title('TES {}'.format(TESNum))
xlabel('Cos(50) x Az')
ylabel('El')
colorbar()
```

```{python}
len(amp_demod)
```

```{python}
"""make vars below dependant on asic"""
tt = a.timeaxis(axistype='pps', asic=asic)
```

```{python}
"""WARNING do not use this cell, need to run each asic individually and combine
so for some reason asic 2 TOD has 8 more entries which can cause a buggy demodulation"""
reload(dl)
### Now do all maps with the same cuts
###
Period = 1.

##### Filtering to be used
lowcut = 0.5
highcut = 70
nharm = 10
notch = np.array([[1.724, 0.005, nharm]])
fourier_cuts = [lowcut, highcut, notch]

amps_demod = np.zeros((256, len(amp_demod)))

for asic in [1,2]:
    tt = a.timeaxis(axistype='pps', asic=asic)
    src = [tt, np.interp(tt, t_src, data_src)]
    for i in range(128):
        print('Mapmaking for Asic {} TES {}'.format(asic,i+1))    
        tod = a.timeline(TES=i+1,asic=asic)

        print('- Demodulation')
        newt_demod, amps_demod[i+128*(asic-1),:], errors_demod = dl.demodulate_methods([tt, tod],
                                                                    1./period, 
                                                                    src_data_in=src,
                                                                    method='demod_quad', remove_noise=True,
                                                                   fourier_cuts=fourier_cuts)

```

```{python}
"""so for some reason asic 1 TOD has 8 more entries which can cause a buggy demodulation
do demod for each asic"""
reload(dl)
### Now do all maps with the same cuts
###
Period = 1.
asic = 1

amps_demoda1 = np.zeros((128, len(amp_demodasic1)))

tt = a.timeaxis(axistype='pps', asic=asic)
src = [tt, np.interp(tt, t_src, data_src)]
for i in range(128):
    print('Mapmaking for Asic {} TES {}'.format(asic,i+1))    
    tod = a.timeline(TES=i+1,asic=asic)

    print('- Demodulation')
    newt_demod, amps_demoda1[i,:], errors_demod = dl.demodulate_methods([tt, tod],
                                                                1./period, 
                                                                src_data_in=src,
                                                                method='demod_quad', remove_noise=True,
                                                               fourier_cuts=fourier_cuts)


```

```{python}
"""so for some reason asic 2 TOD has 8 more entries which can cause a buggy demodulation
do demod for each asic"""
reload(dl)
### Now do all maps with the same cuts
###
Period = 1.
asic = 2

amps_demoda2 = np.zeros((128, len(amp_demodasic2)))

tt = a.timeaxis(axistype='pps', asic=asic)
src = [tt, np.interp(tt, t_src, data_src)]
for i in range(128):
    print('Mapmaking for Asic {} TES {}'.format(asic,i+1))    
    tod = a.timeline(TES=i+1,asic=asic)

    print('- Demodulation')
    newt_demod, amps_demoda2[i,:], errors_demod = dl.demodulate_methods([tt, tod],
                                                                1./period, 
                                                                src_data_in=src,
                                                                method='demod_quad', remove_noise=True,
                                                               fourier_cuts=fourier_cuts)

```

```{python}
print(newt_demod[0:len(amps_demoda1[0,:])].shape)
```

```{python}
print(tt.shape, tod.shape)
```

```{python}
print(amps_demoda1.shape, amps_demoda2.shape)
```

```{python}
print(len(amps_demoda2[:len(amps_demoda1[0,:])]))
```

```{python}
print(amps_demoda2[:,:len(amps_demoda1[0,:])].shape, len(amps_demoda1[0,:]))
```

```{python}
amps_demod = np.vstack([amps_demoda1, amps_demoda2[:,:len(amps_demoda1[0,:])]])
```

```{python}
print(amps_demod.shape)
```

```{python}
"""create maps"""
nmaps = 256
mapdata = np.zeros((256, nel, naz))
#reset this to asic1
newaz = np.interp(newt_demod[0:len(amps_demoda1[0,:])], time_azel, az)
newel = np.interp(newt_demod[0:len(amps_demoda1[0,:])], time_azel, el)

mapdata, azmap, elmap = dl.coadd_flatmap(amps_demod, newaz, newel, 
                                                                filtering=None,
                                                                azmin=azmin, azmax=azmax, 
                                                                elmin=elmin, elmax=elmax, 
                                                                naz=naz,nel=nel)
```

```{python}
print(mapdata.shape)
```

```{python}
"""martins solution"""
for i in range(256):
    print("saving flat map for tes {}".format(i+1))
    FitsArray(mapdata[i,:,:]).save('/sps/hep/qubic/Users/jdmurphy/synthdata/2020-01-14/Flat/imgflat_TESNum_{}.fits'.format(i+1))
```

```{python}
"""save the az el files for flats..."""
from pysimulators import FitsArray as fa
fa(azmap).save('/sps/hep/qubic/Users/jdmurphy/synthdata/2020-01-14/Flat/azimuth.fits')
fa(elmap).save('/sps/hep/qubic/Users/jdmurphy/synthdata/2020-01-14/Flat/elevation.fits')
```

```{python}
"""test the flats"""
import qubic.sb_fitting as sbfit
import matplotlib.pyplot as plt
dirfile = '/sps/hep/qubic/Users/jdmurphy/synthdata/2020-01-14'

c50 = np.cos(np.radians(50))
azmin = -15./c50
azmax = 15./c50
TESNum = 98

flatmap, az, el = sbfit.get_flatmap(TESNum, dirfile, azmin = azmin, azmax=azmax)
AZ, EL = np.meshgrid(az, el)

plt.figure(figsize=(12,16))
plt.subplot(1,3,1)
plt.imshow(flatmap, aspect='equal', origin='lower',
          extent=[np.min(AZ)*c50, np.max(AZ)*c50, np.min(EL), np.max(EL)])
```

```{python}
"""seems okay, now try healpix and TEST before save files"""
# import healpy as hp
# from qubic import demodulation_lib as dl

hpmapa = dl.scan2hpmap(128, newaz*np.cos(np.radians(50)), newel-50, amps_demod[0,:] )
```

```{python}
import healpy as hp
hp.mollview(hpmapa)
hp.gnomview(hpmapa,reso=10,max=np.max(hpmapa)/5,min=0)
```

```{python}
"""for each demodulated signal make a hpmap and save it"""
from qubic.io import write_map
path = '/sps/hep/qubic/Users/jdmurphy/synthdata/2020-01-14/Healpix/'

for tes in np.linspace(0,255, 256, dtype=int):
    tesnum=str(tes+1)
    print("tes idx, tesnum ", tes, tes+1)
    hpmap = dl.scan2hpmap(128, newaz*np.cos(np.radians(50)), newel-50, amps_demod[tes,:])
    write_map(path+'healpix_'+'TESNum_'+tesnum+'.fits', hpmap)
```

```{python}
"""test loading and plotting healpix maps"""
import qubic.sb_fitting as sbfit
directory = '/sps/hep/qubic/Users/jdmurphy/synthdata/2020-01-14'
tes =256
hpmap = sbfit.get_hpmap(tes, directory)
hp.gnomview(hpmap, reso=10, title='TES #{}'.format(tes),cmap='jet',max=np.max(hpmap)/5,min=0)

print(hpmap.shape)
```

```{python}

```
